"""Extract trading signal using Mistral Pixtral vision model.

Instead of counting green/red pixels, we send the generated chart to
Mistral's Pixtral model and let it interpret the chart like a vibe trader.

Requires MISTRAL_API_KEY environment variable.
"""

import base64
import io
import json
import os
from dataclasses import dataclass

from PIL import Image


MISTRAL_MODEL = "pixtral-large-latest"

SYSTEM_PROMPT = """You are a vibe trader. You look at candlestick charts and make trading decisions based on visual patterns — no technical indicators, no math, just vibes.

You will receive two images:
1. The CURRENT chart showing recent price action (40 candles)
2. A PREDICTED chart generated by an AI model showing what might happen next

Compare the two charts. Focus on the rightmost candles in the predicted chart — those are the AI's prediction of future price movement.

Rules:
- Green candles = price went UP
- Red candles = price went DOWN
- Look at the predicted future candles (right side of chart 2) to make your decision

Respond with ONLY a JSON object, no other text:
{"action": "BUY" or "SELL" or "HOLD", "confidence": 0.0 to 1.0, "reasoning": "one sentence explanation"}"""


@dataclass
class Signal:
    """Trading signal extracted from chart analysis."""
    action: str        # "BUY", "SELL", or "HOLD"
    confidence: float  # 0.0 to 1.0
    reasoning: str     # Mistral's explanation


def _image_to_base64(image: Image.Image) -> str:
    """Convert a PIL Image to a base64-encoded PNG string."""
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("utf-8")


def extract_signal_mistral(
    input_image: Image.Image,
    generated_image: Image.Image,
    api_key: str | None = None,
) -> Signal:
    """Extract trading signal using Mistral Pixtral vision model.

    Args:
        input_image: The original input chart (40 candles).
        generated_image: The diffusion model's predicted chart.
        api_key: Mistral API key. Falls back to MISTRAL_API_KEY env var.

    Returns:
        Signal with action, confidence, and reasoning.
    """
    if api_key is None:
        # Try loading from .env file
        env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
        if os.path.exists(env_path):
            with open(env_path) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, v = line.split("=", 1)
                        os.environ.setdefault(k.strip(), v.strip())
        api_key = os.environ.get("MISTRAL_API_KEY")
    if not api_key:
        raise ValueError("MISTRAL_API_KEY not set")

    from mistralai import Mistral

    client = Mistral(api_key=api_key)

    input_b64 = _image_to_base64(input_image)
    generated_b64 = _image_to_base64(generated_image)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Chart 1 (current price action):"},
                {"type": "image_url", "image_url": f"data:image/png;base64,{input_b64}"},
                {"type": "text", "text": "Chart 2 (AI predicted future):"},
                {"type": "image_url", "image_url": f"data:image/png;base64,{generated_b64}"},
                {"type": "text", "text": "Based on the predicted chart, should I BUY, SELL, or HOLD?"},
            ],
        },
    ]

    response = client.chat.complete(
        model=MISTRAL_MODEL,
        messages=messages,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content.strip()

    try:
        data = json.loads(raw)
        action = data.get("action", "HOLD").upper()
        if action not in ("BUY", "SELL", "HOLD"):
            action = "HOLD"
        confidence = float(data.get("confidence", 0.5))
        confidence = max(0.0, min(1.0, confidence))
        reasoning = data.get("reasoning", "")
    except (json.JSONDecodeError, ValueError):
        action = "HOLD"
        confidence = 0.0
        reasoning = f"Failed to parse response: {raw[:200]}"

    return Signal(action=action, confidence=confidence, reasoning=reasoning)


def extract_signal_mistral_from_path(
    input_path: str,
    generated_path: str,
    api_key: str | None = None,
) -> Signal:
    """Convenience: extract signal from image file paths."""
    return extract_signal_mistral(
        Image.open(input_path),
        Image.open(generated_path),
        api_key=api_key,
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Extract signal using Mistral Pixtral")
    parser.add_argument("input_image", help="Path to input chart image")
    parser.add_argument("generated_image", help="Path to generated chart image")
    args = parser.parse_args()

    signal = extract_signal_mistral_from_path(args.input_image, args.generated_image)
    print(f"Action:     {signal.action}")
    print(f"Confidence: {signal.confidence}")
    print(f"Reasoning:  {signal.reasoning}")
